kind: ServiceAccount
apiVersion: v1
metadata:
  name: auth-portal
  namespace: kopeio-auth

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auth-portal
  namespace: kopeio-auth
rules:
- apiGroups: ["auth.kope.io"]
  resources: ["users"]
  verbs: ["get","watch","list","create","update"]
- apiGroups: ["config.auth.kope.io"]
  resources: ["authconfigurations"]
  verbs: ["get","watch","list"]
- apiGroups: ["config.auth.kope.io"]
  resources: ["authproviders"]
  verbs: ["get","watch","list"]
- apiGroups: ["auth.kope.io"]
  resources: ["users"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","watch","list","create","update"]
  resourceNames: ["auth"]
# https://github.com/kubernetes/kubernetes/issues/54079
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "get", "watch"]
# https://github.com/kubernetes/kubernetes/issues/54080
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
# https://github.com/kubernetes/kubernetes/issues/54080


---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auth-portal
  namespace: kopeio-auth
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","watch","list","create","update"]
  resourceNames: ["auth"]
# https://github.com/kubernetes/kubernetes/issues/54079
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "get", "watch"]
# https://github.com/kubernetes/kubernetes/issues/54080
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
# https://github.com/kubernetes/kubernetes/issues/54080


---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auth-portal
  namespace: kopeio-auth
rules:
- apiGroups: ["auth.kope.io"]
  resources: ["users"]
  verbs: ["get","watch","list","create","update"]
- apiGroups: ["config.auth.kope.io"]
  resources: ["authconfigurations"]
  verbs: ["get","watch","list"]
- apiGroups: ["config.auth.kope.io"]
  resources: ["authproviders"]
  verbs: ["get","watch","list"]
- apiGroups: ["auth.kope.io"]
  resources: ["users"]
  verbs: ["get","watch","list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auth-portal
  namespace: kopeio-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: auth-portal
subjects:
- kind: ServiceAccount
  name: auth-portal
  namespace: kopeio-auth

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auth-portal
  namespace: kopeio-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: auth-portal
subjects:
- kind: ServiceAccount
  name: auth-portal
  namespace: kopeio-auth


---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-portal
  namespace: kopeio-auth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-portal
    spec:
      serviceAccountName: auth-portal
      containers:
      - name: auth-portal
        image: kopeio/auth-portal:1.0.20170506
        ports:
        - containerPort: 8080
        command:
        - /auth-portal
        - --v=8
        #- --server=https://auth-api
        #- --insecure-skip-tls-verify

---

apiVersion: v1
kind: Service
metadata:
  name: auth-portal
  namespace: kopeio-auth
spec:
  selector:
    app: auth-portal
  ports:
  - port: 80
    targetPort: 8080
