kind: ServiceAccount
apiVersion: v1
metadata:
  name: auth-api
  namespace: kopeio-auth

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kopeio-auth:auth-api:auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: auth-api
  namespace: kopeio-auth

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kopeio-auth:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: auth-api
  namespace: kopeio-auth

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auth-api
  namespace: kopeio-auth
rules:
- apiGroups: ["auth.kope.io"]
  resources: ["users"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auth-api
  namespace: kopeio-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: auth-api
subjects:
- kind: ServiceAccount
  name: auth-api
  namespace: kopeio-auth

---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: auth-portal
  namespace: kopeio-auth

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auth-portal
  namespace: kopeio-auth
rules:
- apiGroups: ["auth.kope.io"]
  resources: ["users"]
  verbs: ["get","watch","list","create","update"]
- apiGroups: ["config.auth.kope.io"]
  resources: ["authconfigurations"]
  verbs: ["get","watch","list"]
- apiGroups: ["config.auth.kope.io"]
  resources: ["authproviders"]
  verbs: ["get","watch","list"]
- apiGroups: ["auth.kope.io"]
  resources: ["users"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","watch","list","create","update"]
  resourceNames: ["auth"]
# https://github.com/kubernetes/kubernetes/issues/54079
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "get", "watch"]
# https://github.com/kubernetes/kubernetes/issues/54080
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
# https://github.com/kubernetes/kubernetes/issues/54080

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auth-portal
  namespace: kopeio-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: auth-portal
subjects:
- kind: ServiceAccount
  name: auth-portal
  namespace: kopeio-auth


---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auth-portal
  namespace: kopeio-auth
rules:
- apiGroups: ["auth.kope.io"]
  resources: ["users"]
  verbs: ["get","watch","list","create","update"]
- apiGroups: ["config.auth.kope.io"]
  resources: ["authconfigurations"]
  verbs: ["get","watch","list"]
- apiGroups: ["config.auth.kope.io"]
  resources: ["authproviders"]
  verbs: ["get","watch","list"]
- apiGroups: ["auth.kope.io"]
  resources: ["users"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","watch","list","create","update"]
  resourceNames: ["auth"]
# https://github.com/kubernetes/kubernetes/issues/54079
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "get", "watch"]
# https://github.com/kubernetes/kubernetes/issues/54080
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
# https://github.com/kubernetes/kubernetes/issues/54080
